CREATE TABLE MEMBERS (
   MEMBER_NUM NUMBER(10) PRIMARY KEY,
   MEMBER_ID VARCHAR2(20) NOT NULL,
   MEMBER_PW VARCHAR2(100) NOT NULL,
   JOIN_DATE DATE DEFAULT SYSDATE NOT NULL, 
   NATIONAL_ID VARCHAR2(15) NOT NULL,
   MEMBER_ADDR VARCHAR2(100) NOT NULL,
   MEMBER_ADDR_DETAIL VARCHAR2(100),
   MEMBER_ROLE VARCHAR2(20) DEFAULT 'ROLE_CONSUMER',
   IS_AGREE CHAR(1) DEFAULT '1'
);
CREATE SEQUENCE MEMBER_SEQ;

CREATE TABLE CONSUMPTIONS (
	CONSUMPTION_NUM NUMBER PRIMARY KEY NOT NULL,
	CONSUMER_ID VARCHAR2(13) FOREIGN KEY,
	CONS_DATE DATE NOT NULL,
	CONS_ELECTRICITY NUMBER NOT NULL,
	CONS_PROG1 NUMBER,
	CONS_PROG2 NUMBER,
	CONS_PROG3 NUMBER,
	CONS_SMLY NUMBER,
	BILLS_ELEC_TOTAL NUMBER NOT NULL,
	BILLS_BASIC NUMBER NOT NULL,
	BILLS_ELEC_AMOUNT NUMBER NOT NULL,
	BILLS_CLIMATE NUMBER,
	BILLS_FUEL NUMBER
);
CREATE SEQUENCE CONSUMPTION_SEQ;


CREATE TABLE CONSUMERS (
	CONSUMER_ID VARCHAR2(50) PRIMARY KEY NOT NULL,
	MEMBER_ID VARCHAR2(50) FOREIGN KEY,
	KEPCO_CUST_NUM VARCHAR2(50) NOT NULL,
	CUSTOMER_TYPE VARCHAR2(50) NOT NULL,
	CONTRACT_TYPE VARCHAR2(50) NOT NULL
);
CREATE SEQUENCE CONSUMER_SEQ;