--DROP TABLE MEMBERS;
CREATE TABLE MEMBERS(
	MEMBERS_NUM NUMBER(10) PRIMARY KEY 
	, MEMBER_ID VARCHAR2(20) NOT NULL UNIQUE
	, MEMBER_PW VARCHAR2(100) NOT NULL
	, JOIN_DATE DATE DEFAULT SYSDATE
	, NATIONAL_ID VARCHAR2(15) NOT NULL
	, MEMBER_ADDR VARCHAR2(100) NOT NULL
	, MEMBER_ADDR_DETAIL VARCHAR2(100)
	, MEMBER_ROLE VARCHAR2(20) DEFAULT 'CONSUMER' NOT NULL
	, IS_AGREE CHAR(1) DEFAULT 1 NOT NULL
);
CREATE SEQUENCE members_seq;

CREATE TABLE CONSUMERS(
	CONSUMER_ID VARCHAR2(13) PRIMARY KEY
	, MEMBER_ID VARCHAR2(20) NOT NULL REFERENCES MEMBERS(MEMBER_ID)
	, KEPCO_CUST_NUM VARCHAR2(13) NOT NULL
	, CUSTOMER_TYPE VARCHAR2(9) NOT NULL CHECK(CUSTOMER_TYPE IN ('주택용','일반용'))
	, CONTRACT_TYPE VARCHAR2(5) NOT NULL CHECK(CONTRACT_TYPE IN ('저압','고압','갑1','갑2','을'))
);

CREATE TABLE CONSUMPTIONS(
	CONSUMER_ID VARCHAR2(13) PRIMARY KEY REFERENCES CONSUMERS(CONSUMER_ID)
	, CONS_DATE DATE NOT NULL
	, CONS_ELECTRICITY NUMBER NOT NULL
	, CONS_PROG1 NUMBER
	, CONS_PROG2 NUMBER
	, CONS_PROG3 NUMBER
	, CONS_SMLY NUMBER
	, BILLS_ELEC_TOTAL NUMBER NOT NULL
	, BILLS_BASIC NUMBER NOT NULL
	, BILLS_ELEC_AMOUNT NUMBER NOT NULL
	, BILLS_CLIMATE NUMBER NOT NULL
	, BILLS_FUEL NUMBER NOT NULL
);
CREATE TABLE SOLAR_MODULE(
	MODULE_ID VARCHAR2(30) PRIMARY KEY
	, MODULE_NAME VARCHAR2(20)
	, MODULE_SOH NUMBER
);


CREATE TABLE PRODUCERS(
	PRODUCER_ID VARCHAR2(13) PRIMARY KEY
	, MEMBER_ID VARCHAR2(20) NOT NULL REFERENCES MEMBERS(MEMBER_ID)
	, MEMBER_ADDR VARCHAR2(100) NOT NULL
	, LOCATION_X NUMBER(13,10) NOT NULL
	, LOCATION_Y NUMBER(13,10) NOT NULL
	, INSTALLED_CAPACITY NUMBER(3) NOT NULL
	, MODULE_ID VARCHAR2(10) REFERENCES SOLAR_MODULE(MODULE_ID)
);

CREATE TABLE PRODUCTIONS(
	PRODUCER_ID VARCHAR2(13) PRIMARY KEY REFERENCES PRODUCERS(PRODUCER_ID)
	, PROD_DATE DATE NOT NULL
	, PROD_ELECTRICITY NUMBER NOT NULL
	, PROD_DATE_MONTH CHAR(2)	
);

CREATE SEQUENCE SALES_SEQ;
CREATE TABLE SALES_BOARD(
	SALES_NUM NUMBER PRIMARY KEY
	, MEMBER_ID VARCHAR2(20) REFERENCES MEMBERS(MEMBER_ID)
	, TITLE VARCHAR2(100) NOT NULL
	, CONTENTS VARCHAR2(4000)
	, SALES_STARTMONTH DATE NOT NULL
	, SALES_ENDMONTH DATE NOT NULL
	, TOTAL_MONTH NUMBER
	, TOTAL_AMOUNT NUMBER NOT NULL
	, TOTAL_PRICE NUMBER NOT NULL
	, AVG_AMOUNT NUMBER
	, STATUS CHAR(1) DEFAULT 0
	, WRITE_DATE DATE DEFAULT SYSDATE
);

CREATE TABLE SALES_INQUIRY(
	SALES_NUM NUMBER PRIMARY KEY REFERENCES SALES_BOARD(SALES_NUM)
	, MEMBER_ID VARCHAR2(20) REFERENCES MEMBERS(MEMBER_ID)
	, IS_SELLER CHAR(1) NOT NULL
	, CONTENT VARCHAR2(4000) NOT NULL
	, INQUIRY_DATE DATE DEFAULT SYSDATE
	, IS_READ CHAR(1) 
);

CREATE SEQUENCE TRADE_SEQ;
CREATE TABLE TRADE(
	TRADE_NUM NUMBER PRIMARY KEY
	, SALES_NUM NUMBER REFERENCES SALES_BOARD(SALES_NUM)
	, CONS_MEMBER_ID VARCHAR2(20) NOT NULL
	, CONS_NATIONAL_ID VARCHAR2(15) NOT NULL
	, PROD_MEMBER_ID VARCHAR2(20) NOT NULL
	, PROD_NATIONAL_ID VARCHAR2(15) NOT NULL
	, AGREED_STARTDATE DATE NOT NULL
	, AGREED_ENDDATE DATE NOT NULL
	, AGREED_TOTAL_AMOUNT NUMBER NOT NULL
	, AGREED_TOTAL_PRICE NUMBER NOT NULL
	, TRADE_DATE DATE DEFAULT SYSDATE
	, TRADE_DETAIL VARCHAR2(4000) DEFAULT NULL
	, STATUS VARCHAR2(20) DEFAULT 'AGREED' CHECK(STATUS IN ('AGREED','CANCELED','COMPLETED'))
)


-- 나머지 테이블(weather, weather_point, kepco_decision, prices 엔티티는 구공드/데이터 에서 다운로드 받아서 import)
SELECT * FROM KEPCO_DECISION kd ;
SELECT * FROM WEATHER_POINT wp ;
SELECT * FROM WEATHER_서울_강릉_울산 w서강울 ;
SELECT * FROM WEATHER_서울_강릉_울산
ORDER BY 1, 3;